version: '3'
services:
    node:
        build:
            context: ./docker
            dockerfile: node
        volumes:
            - .:/usr/local/src/pl-snakes
        entrypoint: ["parcel", "index.html"]
        ports:
            - "1234:1234"